### ISSUE TITLE
Did you mean CppUTest instead of CppTest?

### ISSUE THREAD

**Issue by mattkelly** [noahp/noah-c#1]
Great little repo you have here! This is helpful and I look forward to seeing it evolve.

Did you mean [CppUTest](https://cpputest.github.io/) instead of CppTest in your list of unit test frameworks? I'm not familiar with the latter, but it doesn't appear to have some of the features you mentioned, such as a mocking system. CppUTest does have these features.

**Comment by noahp** [comment]
Ah, yes I did! thanks much!
